env:
  node: true
root: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
rules:
  valid-jsdoc: error
  prettier/prettier: error
overrides:
  - files:
      - "**/__tests__/**"
      - "**/*.test.js"
    env:
      jest: true
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
  - files:
      - "visu/*"
      - "**/*.test.js"
    env:
      browser: true
    rules:
      func-names: 0
      import/extensions: ["error", "always"]